version: "3.9"

volumes:
  boilerplate_db_migrations:
    name: boilerplate_db_migrations
  boilerplate_logs:
    name: boilerplate_logs

services:
  api:
    image: "${API_IMAGE}"
    container_name: api
    build:
      context: ../../
      dockerfile: backend/Dockerfile
      cache_from:
        - ${API_IMAGE}
    ports:
      - 5000:5000
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - TITLE=${TITLE}
      - CLIENT_ROOT_PATH=${CLIENT_ROOT_PATH}
      - ADMIN_ROOT_PATH=${ADMIN_ROOT_PATH}
      - CLIENT_URL=${CLIENT_URL}
      - API_BASE_URL=${API_BASE_URL}
      - API_URL=${API_URL}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}

      - OPERA_LOG_ENCRYPT_SECRET_KEY=${OPERA_LOG_ENCRYPT_SECRET_KEY}
      - OAUTH2_GITHUB_CLIENT_ID=${OAUTH2_GITHUB_CLIENT_ID}
      - OAUTH2_GITHUB_CLIENT_SECRET=${OAUTH2_GITHUB_CLIENT_SECRET}
      - OAUTH2_LINUX_DO_CLIENT_ID=${OAUTH2_LINUX_DO_CLIENT_ID}
      - OAUTH2_LINUX_DO_CLIENT_SECRET=${OAUTH2_LINUX_DO_CLIENT_SECRET}
      - CELERY_BROKER_REDIS_DATABASE=${CELERY_BROKER_REDIS_DATABASE}
      - CELERY_BACKEND_REDIS_DATABASE=${CELERY_BACKEND_REDIS_DATABASE}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_CLOUD_URL=${MINIO_CLOUD_URL}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - EMAILS_FROM_NAME=${EMAILS_FROM_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

    volumes:
      - boilerplate_db_migrations:/app/backend/alembic/versions
      - boilerplate_logs:/app/backend/log
